# Generated by Django 5.1.6 on 2025-02-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpannel',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpannel',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpannel',
            name='user_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
