# Generated by Django 5.1.6 on 2025-02-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpannel_user_first_name_userpannel_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpannel',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='userpannel',
            name='user_last_name',
        ),
        migrations.RemoveField(
            model_name='userpannel',
            name='user_username',
        ),
    ]
