# Generated by Django 5.1.6 on 2025-02-23 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userpannel_slug_userpannel_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpannel',
            old_name='first_name',
            new_name='user_first_name',
        ),
        migrations.RenameField(
            model_name='userpannel',
            old_name='last_name',
            new_name='user_last_name',
        ),
        migrations.RemoveField(
            model_name='userpannel',
            name='username',
        ),
        migrations.AddField(
            model_name='userpannel',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userpannel',
            name='user_username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userpannel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
