# Generated by Django 5.1.6 on 2025-02-24 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_first_name_userpannel_user_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpannel',
            name='user_first_name',
        ),
        migrations.RemoveField(
            model_name='userpannel',
            name='user_last_name',
        ),
        migrations.RemoveField(
            model_name='userpannel',
            name='user_username',
        ),
        migrations.AddField(
            model_name='userpannel',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userpannel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='userpannel',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='userpannel',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userpannel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pannel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
