# Generated by Django 5.1.5 on 2025-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteblog',
            name='token',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
