# Generated by Django 5.1.5 on 2025-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0004_alter_siteblog_slug3'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteblog',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='siteblog/'),
        ),
    ]
