# Generated by Django 5.1.5 on 2025-02-13 06:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0005_siteblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblog',
            name='token',
            field=models.CharField(blank=True, default='', max_length=6, null=True, unique=True),
        ),
    ]
