# Generated by Django 5.1.5 on 2025-02-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0007_alter_siteblog_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblog',
            name='token',
            field=models.CharField(blank=True, default='IPO4f0', max_length=6, null=True, unique=True),
        ),
    ]
