# Generated by Django 5.1.5 on 2025-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0009_alter_siteblog_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='siteblog/'),
        ),
    ]
