# Generated by Django 5.1.5 on 2025-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0010_alter_siteblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblog',
            name='slug3',
            field=models.SlugField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='siteblog',
            name='token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
