# Generated by Django 5.1.5 on 2025-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0011_alter_siteblog_slug3_alter_siteblog_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblog',
            name='token',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
