# Generated by Django 5.1.5 on 2025-02-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0012_alter_siteblog_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteblog',
            old_name='slug3',
            new_name='slug',
        ),
    ]
