# Generated by Django 5.1.6 on 2025-02-20 05:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0013_rename_slug3_siteblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteblog',
            name='mm',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
