# Generated by Django 5.1.6 on 2025-02-20 05:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0014_siteblog_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteblog',
            name='mm',
        ),
        migrations.AlterField(
            model_name='siteblog',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='ورود متن'),
        ),
    ]
