# Generated by Django 5.1.6 on 2025-02-20 08:31

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteblog', '0015_remove_siteblog_mm_alter_siteblog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblog',
            name='content',
            field=django_quill.fields.QuillField(default='', verbose_name='ورود متن'),
        ),
    ]
