# Generated by Django 5.1.6 on 2025-02-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0003_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصولات', 'verbose_name_plural': 'محصول'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
