# Generated by Django 5.1.6 on 2025-02-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0004_alter_product_options_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
