# Generated by Django 5.1.6 on 2025-02-08 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0005_rename_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(6)]),
        ),
    ]
