# Generated by Django 5.1.6 on 2025-02-08 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0006_alter_product_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)]),
        ),
    ]
