# Generated by Django 5.1.6 on 2025-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0007_alter_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_translator',
            field=models.BooleanField(default=False, verbose_name='مترجم دارد ؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='قیمت تخفیف خورده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='translator',
            field=models.CharField(default='-', max_length=100, verbose_name='نام مترجم'),
        ),
    ]
