# Generated by Django 5.1.6 on 2025-02-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0008_product_is_translator_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Inventory',
            field=models.BooleanField(default=True, verbose_name='موجودی'),
        ),
    ]
