# Generated by Django 5.1.5 on 2025-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0009_alter_product_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
    ]
