# Generated by Django 5.1.5 on 2025-02-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0010_site_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_banner',
            options={'verbose_name': 'تصاویر کتب بنر', 'verbose_name_plural': 'تصاویر کتب بنر'},
        ),
        migrations.AlterField(
            model_name='site_banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='تصویر کتب موجود در بنر'),
        ),
    ]
