# Generated by Django 5.1.5 on 2025-02-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0011_alter_site_banner_options_alter_site_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unfill_score',
            field=models.IntegerField(default=0),
        ),
    ]
