# Generated by Django 5.1.5 on 2025-02-13 07:43

import Shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0015_alter_product_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='token',
            field=models.CharField(blank=True,  max_length=6, null=True, unique=True),
        ),
    ]
