# Generated by Django 5.1.5 on 2025-02-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0022_alter_product_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='token',
        ),
    ]
